### ISSUE TITLE
Free to use?

### ISSUE THREAD

**Issue by AdySan** [koofka/singleproperty_redux#1]
Hello,

I was looking for a single property listing template and stumbled upon this project. I ran it, looks pretty good. However, seems like it is heavily REMAX branded, so is this free to use? 

If you'd recommend something similar but rather simpler boilerplate stuff, that would be cool too!

Thanks,
Ady

**Comment by koofka** [comment]
Hey Ady,

Sorry for the late reply, haven't been active for a couple weeks.  So far this is still a work in progress for a particular ReMax agent I work with and would prefer to keep it closed until its better optimized for distribution  / boilerplate use.  Thanks for checking in though!
